#!/usr/bin/env bash

# display information for the specified subdomain
display_info() {
    local subdomain=$1
    local domain=$2

    dig_output=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION/{getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
    local domain=$1
    local subdomain=$2

    subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -n "$subdomain" ]; then
        display_info "$subdomain" "$domain"
    else
        for sub in "${subdomains[@]}"; do
            display_info "$sub" "$domain"
        done
    fi
}

if [ "$#" -eq 1 ]; then
    main "$1"
elif [ "$#" -eq 2 ]; then
    main "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
