#!/usr/bin/env bash
# Install nginx web server

apt-get update -y
apt-get install nginx -y
ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing nginx configuration
sudo nginx -t

sudo service nginx reload
