#!/usr/bin/env bash
# Install nginx web server

# Set Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Write "Hello World!" to the default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test nginx configuration
nginx -t

# Reload nginx to apply changes
service nginx reload
