#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get update
apt-get install nginx -y

tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	server_name _;
        add_header X-Served-By "${HOSTNAME}";
	location / {
		try_files $uri $uri/ =404;
	}
}
EOF
service nginx restart
	
