#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend abayo_frontend
	bind *:80
	mode http
	default_backend abayo_backend
backend abayo_backend
	balance roundrobin
	server 49303-web-01 54.158.202.47:80 check
	server 49303-web-02 52.204.60.176:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
