#!/usr/bin/env bash
# Script to fix Nginx not listening on port 80 issue

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
