#!/usr/bin/env bash
# This script creates a file
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo bash -c "echo $$ > /var/run/myscript.pid"
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/myscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
