#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.

pids=$(pgrep -f bash)

for pid in $pids; do
	pname=$(cat /proc/$pid/cmdline | tr '\0' ' ')
	echo "$pid $pname"
done
