#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.

pids=$(pgrep -f bash)

for pid in $pids; do
	pname=$(tr '\0' ' ' < "/proc/$pid/cmdline")
	echo "$pid $pname"
done
