#!/usr/bin/env bash
# This script displays numbers from 1 to 100.

counter=1

while ((counter <= 100)); do
	if ((counter % 3 == 0 && counter % 5 ==0)); then
		echo "FizzBuzz"
	elif ((counter % 3 == 0)); then
		echo "Fizz"
	elif (( counter % 5 == 0)); then
		echo "Buzz"
	else
		printf "%d\n" "$counter"
	fi
	((counter++))
done
	
