#!/usr/bin/env bash
# script that runs nginx user and listens to all active IPs.

sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default

sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

id -u nginx &>/dev/null || useradd -r -s /bin/false nginx

chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /etc/nginx

service restart nginx
