#!/usr/bin/env bash
# script that runs nginx user as nginx and listens to all active IPs on port 8080.

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf

sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-available/default

chown -R nginx:nginx /etc/nginx.conf

pkill apache2

sudo -u nginx service nginx restart
