#!/usr/bin/env bash
# script that runs nginx user as nginx and listens to all active IPs on port 8080.

id -u nginx &>/dev/null || useradd -r -s /bin/false nginx

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-available/default

chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /etc/nginx

service restart nginx
